//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HavaYoluApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pilot
    {
        public int PilotNo { get; set; }
        public string PilotAdi { get; set; }
        public Nullable<int> PilotYas { get; set; }
        public Nullable<int> PilotTecrube { get; set; }
        public Nullable<int> UcakNo { get; set; }
    }
}
