//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HavaYoluApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sirket
    {
        public int SirketNo { get; set; }
        public string SirketAdi { get; set; }
        public string Sirketİl { get; set; }
        public Nullable<int> SirketKurulus { get; set; }
    }
}
